apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testchatbot2-jul25 
  janus-idp.io/tekton: testchatbot2-jul25
  backstage.io/kubernetes-id: testchatbot2-jul25
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testchatbot2-jul25
resources: 
- application-dev.yaml